### ISSUE TITLE
Write an App Store description. 

### ISSUE THREAD

**Issue by cambardell** [cambardell/Footnote#16]
Add a text file with an App Store description.

**Comment by M1zz** [comment]
Hi im Leeo. 

Can I get this issue?

**Comment by cambardell** [comment]
Absolutely, thanks @M1zz! The best solution is probably just a text file for now. Eventually we can integrate with Fastlane.

**Comment by M1zz** [comment]
@cambardell Here by comment? or you mean add description file and make PR?

**Comment by cambardell** [comment]
@M1zz A description file and PR would be best!

**Comment by M1zz** [comment]
@cambardell OK I got it Thanks!
