### ISSUE TITLE
Support for different types of media

### ISSUE THREAD

**Issue by cambardell** [cambardell/Footnote#17]
The current author, title, quote setup only corresponds to books. When creating a quote, it should be possible to select different media types such as podcasts, movies, tv shows, etc. 

I've labeled this as "good first issue" for now, but since this requires changes across a large part of the app, it may be better for more experienced contributors, or should be split up into smaller problems.

**Comment by cpabbathi** [comment]
I am interested in working on this issue. I will work on a document with all my ideas/proposals and send it your way. You can make your decision based on that. Thanks!

**Comment by cambardell** [comment]
@cpabbathi Sounds good, thanks! I'll be assigning issues on Oct 1. For now, you can register for Hacktoberfest and create Issues to make feature requests and bug reports.

**Comment by cpabbathi** [comment]
Thank you!
