### ISSUE TITLE
Export to social media. 

### ISSUE THREAD

**Issue by cambardell** [cambardell/Footnote#18]
Currently, quotes can be exported and saved to the photo library. This feature would be more useful if it supported export to social media, mostly likely Twitter and Instagram.

**Comment by JapneetSingh5** [comment]
Hi, I am very excited to contribute to this app! I think this issue would be a good starting point for me (although there are a couple of others that I really want to work on too). 
In addition to adding share options, I think adding Navigation Bars to all views and explicit Done/ Dismiss buttons to the sheets is also a good idea. 
Let me know what you think of it. 
I plan to start working on this later today.

**Comment by cambardell** [comment]
Hi @JapneetSingh5 , I'm not assigning issues until October 1st, to better line up with Hacktoberfest. I posted the repo early so that everyone could have a chance to read the documentation, familiarize themselves with the project, and create some issues. So please hold off on writing any code for now 😊

**Comment by JapneetSingh5** [comment]
Sure. Thankyou!

**Comment by cambardell** [comment]
@JapneetSingh5 Do you still want to take this issue?

**Comment by JapneetSingh5** [comment]
yep, I'll take this!

**Comment by cambardell** [comment]
Assigned, thanks!
