### ISSUE TITLE
Text in textfield not visible in dark mode

### ISSUE THREAD

**Issue by EcMscS** [cambardell/Footnote#20]
**Describe the bug**
The text in 3 textfields do not change color when changed to dark mode. The text becomes invisible to the user in dark mode.

**To Reproduce**
1. Go to add quote screen
2. Click on text textfield
3. Type the text, the color of the text is white which prevents it from being visible to the user. 
4. When change to light mode the text in the textfield appears
5. See Attached Screenshot

**Expected behavior**
Text in 3 textfields, text, title, and author should automatically adjust colors when dark and light modes are switched.  

**Screenshots**
![Dark Mode](https://user-images.githubusercontent.com/3925740/94202780-298caa00-fe73-11ea-92c6-2ebca110eb66.png)
![Light Mode](https://user-images.githubusercontent.com/3925740/94202785-2bef0400-fe73-11ea-96c2-736778368dab.png)

**Smartphone (please complete the following information):**
 - Device: iPhone 7 Plus
 - iOS: 14

**Additional context**
None

**Comment by cambardell** [comment]
Thanks a lot for opening an issue. This would be a good first issue for someone new to SwiftUI. I've tagged it as such.

**Comment by rarcilla** [comment]
Interested in working on this if it's still available!

**Comment by cambardell** [comment]
Sure @rarcilla, thanks!
