### ISSUE TITLE
Possible to save empty quotes and author fields

### ISSUE THREAD

**Issue by JapneetSingh5** [cambardell/Footnote#21]
**Describe the bug**
Theres no check against saving empty empty text, title and author entries.

**To Reproduce**
1. Open app
2. Click on '+'
3. Click on 'Save changes'

**Expected behavior**
An alert indicating that empty fields are not allowed.

**Screenshots**
![image](https://user-images.githubusercontent.com/54809290/94204052-24b11000-fede-11ea-96e5-e4b12ef2f118.jpeg)

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: iOS14

**Comment by cambardell** [comment]
Thanks, this is a good one. Marking it good first issue.

**Comment by rarcilla** [comment]
Interested in this issue, I'm new to OSS!

**Comment by cambardell** [comment]
It's yours @rarcilla 👍. Just a reminder if you're participating in Hacktoberfest, your PRs won't count towards your total until Oct 1. Also you can contact me at anytime, my info is in the readme.
