### ISSUE TITLE
Dimiss Add Quote sheet when the Save button is pressed

### ISSUE THREAD

**Issue by rarcilla** [cambardell/Footnote#23]
**Is your feature request related to a problem? Please describe.**
There is no indication/confirmation that a quote is saved unless the user dismisses the sheet to view the list of quotes and see that it has been added there.

**Describe the solution you'd like**
It'd be nice to have the Add Quote sheet dismissed when the Save button is pressed to communicate to the user that the button has triggered an action. But one question to consider is whether a user is able to add multiple quotes once the sheet is opened, or only one at a time (if it's the former, the alternative described below is a better work around).

**Describe alternatives you've considered**
A confirmation message in the form of a text label underneath the Save button.

**Comment by VPhung24** [comment]
Hey, I'd be willing to pick this up! Let me know what I can do.

**Comment by cambardell** [comment]
Sure @VPhung24 👍
