### ISSUE TITLE
Add an onboarding experience. 

### ISSUE THREAD

**Issue by cambardell** [cambardell/Footnote#25]
**Is your feature request related to a problem? Please describe.**
When a user first opens the app, there is no indication of functionality or guidance on what to do. 

**Describe the solution you'd like**
Upon first launch, the app should welcome the user and somehow indicate functionality, such as guiding the user to add a quote. A good start would be to store a boolean that indicates if it is the user's first launch in UserDefaults, and present an onboarding screen at the top level of the view stack if it is.

**Comment by cambardell** [comment]
@rajhraval1 Has volunteered to take this issue.

**Comment by rajhraval1** [comment]
Sure!, will give a PR soon👍🏻
