### ISSUE TITLE
+ should be in the navigation bar

### ISSUE THREAD

**Issue by VPhung24** [cambardell/Footnote#29]
**Is your feature request related to a problem? Please describe.**
it's more intuitive in iOS for the + button to be in the navigation bar. Not a button in the lower right hand corner

**Describe the solution you'd like**
The button should be the left navigation button

**Comment by VPhung24** [comment]
in #28 but should be a feature request

**Comment by cambardell** [comment]
Thanks @VPhung24, assigned!

**Comment by cambardell** [comment]
I think this means we can remove the ZStack from ContentView. I might be wrong but I think it's only purpose was that floating button.

**Comment by VPhung24** [comment]
makes sense. on it!
