### ISSUE TITLE
List view has an ugly border around it in iOS 14

### ISSUE THREAD

**Issue by cambardell** [cambardell/Footnote#31]
**Describe the bug**
Starting in iOS 14 and Xcode 12, the main list in ContentView has a border. Makes the list look like a box. Below is what it looks like now, and how it used to look. 

**Now**
<img width="200" alt="Screen Shot 2020-09-29 at 8 04 50 PM" src="https://user-images.githubusercontent.com/15818601/94628822-09a02080-028f-11eb-828a-64146bac7658.png">

**Then**
<img width="200" alt="Screen Shot 2020-09-29 at 8 04 50 PM" src="https://user-images.githubusercontent.com/15818601/94629051-ac589f00-028f-11eb-9aec-678d3a08cf46.png">

**Proposed fix**
Figure out if this is an iOS 14 issue, or accidentally caused by another change. Remove border and make list fill given area.

**Comment by JapneetSingh5** [comment]
Adding an explicit .listStyle() Modifier fixes this problem.
ref. https://developer.apple.com/documentation/swiftui/liststyle

**Comment by cambardell** [comment]
Thanks @JapneetSingh5 somehow missed that with all the new changes this summer. I'll make this change later.
