### ISSUE TITLE
Share View Layout Issue

### ISSUE THREAD

**Issue by rajhraval1** [cambardell/Footnote#33]
The current version of Footnote produces a layout issue in iPhone SE (1st Generation).

When the users clicks on "Share Quote", a sheet appears to customise the Footnote (Quote).
The submit button is not properly be seen on the screen.

<img width="200" alt="iPhone SE" src="https://user-images.githubusercontent.com/35184001/94770860-55f47900-03d3-11eb-8caf-bee8f50626ab.png">

Hope, it gets resolved.

**Comment by JapneetSingh5** [comment]
Hi, Ill be working on this View. Thanks for bringing this up! 🙌🏻

**Comment by cambardell** [comment]
Thanks @rajhraval1. I'm assigning this to @JapneetSingh5 since it's closely related to #18 and one PR will probably close both.
