### ISSUE TITLE
Settings tab for app settings and contributions screen

### ISSUE THREAD

**Issue by JapneetSingh5** [cambardell/Footnote#42]
**Is your feature request related to a problem? Please describe.**
As the app becomes a bit more complex, I think having a tab view and a dedicated Settings screen would be a wise decision.

**Describe the solution you'd like**
The settings screen can be home to a menu containing the contributors' screen, developer information, app info and most importantly app wide defaults like DarkMode/LightMode/AutomaticThemeSwitch and perhaps a setting to change the app wide accent color. Possibly, choosing between a variety of app icons and widget controls can be added as well.

**Comment by cambardell** [comment]
Good call, I'll take this one myself.
