### ISSUE TITLE
Add a setting for changing the colour theme. 

### ISSUE THREAD

**Issue by cambardell** [cambardell/Footnote#46]
Global setting for change the default colour from red. 

Implementing this feature would require: 
* Adding a list of nice looking colours. 
* Adding a global environment var with the user's selected colour, and saving. Probably in UserDefaults
* Changing all colour modifiers to the global var.

**Comment by rarcilla** [comment]
just curious, is this possibly a duplicate of #22 , or at least depend on the completion of it?

**Comment by cambardell** [comment]
Oh you’re right @rarcilla, I forgot that issue existed. Closing this one!
