### ISSUE TITLE
Add about section to settings. 

### ISSUE THREAD

**Issue by cambardell** [cambardell/Footnote#48]
Add an about section to the settings screen, with a description of how the app was developed as an open source project, a link to this repo, and other app info, such as version number.

**Comment by stevenanthonyrevo** [comment]
@cambardell I would like to take on this issue.

**Comment by cambardell** [comment]
Thanks Steven, I've assigned you!

**Comment by stevenanthonyrevo** [comment]
Worked on creating the settings panel #50. 

@cambardell Thanks for letting me tackle this, please review the PR and let me if there is anymore Swift UI work needs to be done on the panel itself. 

I've included a description with an icon already, I may need some more suggestions on pulling the version number dynamically.

**Comment by cambardell** [comment]
I'll get to it today, thanks @stevenanthonyrevo
