### ISSUE TITLE
Adding a Swift Linter to enforce a proper code style.

### ISSUE THREAD

**Issue by rajhraval1** [cambardell/Footnote#52]
For better readability of the code, I suggest we can use a Linter, to maintain the codebase and code-style proper.

Example: https://github.com/realm/SwiftLint

**Comment by pushpinderpalsingh** [comment]
Hey, Can I work on this issue? Personally, I have not worked on Linter, but I think I can figure it out.

**Comment by cambardell** [comment]
Works for me @pushpinderpalsingh, it fits with your other dev tool work. Thanks @rajhraval1, this will help a ton.
