### ISSUE TITLE
Replacing present search bar by a native, pull down to search style search bar

### ISSUE THREAD

**Issue by JapneetSingh5** [cambardell/Footnote#62]
Hi, I found a way to implement a native search bar in SwiftUI which hides the search bar until the view is pulled down, mimicking the behavior found commonly in iOS like in spotlight and the settings app.
Should be a nice replacement, let me know what you think.
![](http://blog.eppz.eu/wp-content/uploads/Create_a_SwiftUI_search_text_field_in_the_List.jpg)

**Comment by cambardell** [comment]
This looks great, there's an issue for search open here: #63

**Comment by JapneetSingh5** [comment]
Can you assign that to me?
